"""database

Revision ID: f985694be776
Revises: 
Create Date: 2025-11-15 09:20:50.460548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f985694be776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('classes_id_enseignant_fkey'), 'classes', type_='foreignkey')
    op.drop_column('classes', 'id_enseignant')
    op.drop_index(op.f('ix_enseignants_user_id'), table_name='enseignants')
    op.create_index(op.f('ix_enseignants_id_enseignant'), 'enseignants', ['id_enseignant'], unique=False)
    op.drop_constraint(op.f('enseignants_id_matiere_fkey'), 'enseignants', type_='foreignkey')
    op.drop_column('enseignants', 'id_matiere')
    op.drop_constraint(op.f('etudiants_id_classe_fkey'), 'etudiants', type_='foreignkey')
    op.create_foreign_key(None, 'etudiants', 'classes', ['id_classe'], ['id_classe'], ondelete='SET NULL')
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('actif', 'inactif', name='userstatus'),
               nullable=False,
               existing_server_default=sa.text("'actif'::userstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('actif', 'inactif', name='userstatus'),
               nullable=True,
               existing_server_default=sa.text("'actif'::userstatus"))
    op.drop_constraint(None, 'etudiants', type_='foreignkey')
    op.create_foreign_key(op.f('etudiants_id_classe_fkey'), 'etudiants', 'classes', ['id_classe'], ['id_classe'])
    op.add_column('enseignants', sa.Column('id_matiere', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('enseignants_id_matiere_fkey'), 'enseignants', 'matieres', ['id_matiere'], ['id_matiere'])
    op.drop_index(op.f('ix_enseignants_id_enseignant'), table_name='enseignants')
    op.create_index(op.f('ix_enseignants_user_id'), 'enseignants', ['id_enseignant'], unique=False)
    op.add_column('classes', sa.Column('id_enseignant', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('classes_id_enseignant_fkey'), 'classes', 'enseignants', ['id_enseignant'], ['id_enseignant'])
    # ### end Alembic commands ###
